### ISSUE TITLE
Interpreting output of 3d data.

### ISSUE THREAD

**Issue by ameydesai** [pykalman/pykalman#14]
I have a data in the form [(varx1,vary1,varz1),.....,(varx100,vary100,varz100)]

There are more than 100 values, I have given 100 here for example.

I'm looking spatio-temporal data.

The output I get after running kalmanfilter.smooth or filter is a 2d list. I'm not sure how to interpret it. Can you please guide me.

**Comment by NBELInnovationWorkshops** [comment]
Hi @duckworthd ,

I am trying to do something similar to the OP here but I am a little confused with the inputs to the KalmanFilter object. 

I have a numpy array, called _alignedstack_, which represents 256x256 pixel images taken over time.  I am going to use the Kalman filter as a low-pass filter to reduce noise in the "video" as per your comment: 

```{Python}
tm = np.zeros([256,256,61])
for i in range(alignedstack.shape[0]-1):
    tm[:,:,i] = lstsq(a = alignedstack[i,:,:], b = alignedstack[i+1,:,:])[0]
kf=KalmanFilter(transition_matrices  = tm)
```

When I attempt to smooth the "image stack", using:

```{Python}
kf.smooth(alignedstack)
```

I get _ValueError: operands could not be broadcast together..._ 

Any chance you can point me in the right direction?

Thanks.

Best,
Noah
