### ISSUE TITLE
Dependencies for documentation

### ISSUE THREAD

**Issue by NeroBurner** [pykalman/pykalman#45]
In the installation guide https://pykalman.github.io/#installation the following is stated
- Sphinx (for generating documentation)
- numpydoc (for generating documentation)

Can someone explain to me for what documentation these packages are needed? When I want to just use pykalman can I do it without installing sphinx and numpydoc (are they optional)?

**Comment by sanjayankur31** [comment]
These deps are required only to generate docs from the files given in the doc directory (refer to the Makefile in there). So, yeah, if you don't want to generate docs, you can skip them.
