### ISSUE TITLE
masked array error

### ISSUE THREAD

**Issue by xieliaing** [pykalman/pykalman#49]
loglikelihoods[i] = kf.loglikelihood(data.observations) incurred masked array error in scipy linalg module.

This needs to be changed to loglikelihoods[i] = kf.loglikelihood(data.observations.data)

**Comment by JesseLivezey** [comment]
I get problems from this line:
https://github.com/pykalman/pykalman/blob/8d3f8e498b64d902016a0216bf2bcc8b262d917b/pykalman/utils.py#L73
I wrapped the inputs to the linalg function in np.asarray(a) and things worked.

**Comment by toinsson** [comment]
I get the error in plot_em.py. Can you provide the code to fix it @JesseLivezey ?

**Comment by JesseLivezey** [comment]
https://gist.github.com/JesseLivezey/5d80ef651e75b21a7079

**Comment by tuananhle7** [comment]
Is this now merged?
