### ISSUE TITLE
Question: Can transition/observation covariance vary deterministically in time.

### ISSUE THREAD

**Issue by AShrivats** [pykalman/pykalman#78]
I was looking to use the pykalman package for some research work. I read through the help documentation (https://pykalman.github.io/#pykalman.KalmanFilter) and I noticed that the data types of the transition_covariance and observation_covariance matrices are stated as '[n_dim_state, n_dim_state] array-like'

This would seem to suggest that they must be constant over the number of time-steps, however, the image below taken from the same documentation seems to suggest that these can be deterministically time-varying.
![image](https://user-images.githubusercontent.com/36423949/44548898-66fb3800-a6ed-11e8-9975-fadc9fb5fee2.png)

Which one is accurate?

**Comment by AShrivats** [comment]
The user guide says that there is currently no support for time-varying covariance matrices.

**Comment by chanshing** [comment]
> The user guide says that there is currently no support for time-varying covariance matrices.

Have you actually tried to input a list of covariances? It seems that the package still works for such case as there is really nothing needed to be changed. Perhaps the EM algorithm is the part that wouldn't work -- I haven't tried that.
